---
name: Terraform Destroy
on:
    workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform Destroy
        uses: dflook/terraform-destroy@v1
        continue-on-error: true
        with:
          path: terraform/
          backend_config: >
            access_key=${{ secrets.AWS_ACCESS_KEY_ID }},
            secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }},
            bucket=${{ secrets.AWS_BUCKET }},
