---
name: Terraform Apply
on:
    workflow_dispatch:

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Run Terraform Apply
          uses: dflook/terraform-apply@v1
          with:
            path: terraform/
            auto_approve: true
            variables: |
              access_key="${{ secrets.AWS_ACCESS_KEY_ID }}"
              secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              bucket="${{ secrets.AWS_BUCKET }}"
              region="${{ secrets.AWS_REGION }}"
