---
name: Terraform Runner
on:
    workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform-lint:
    name: Lint and Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Format
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ./terraform

      - name: Terraform Validate
        uses: dflook/terraform-validate@v1
        with:
          path: ./terraform

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Terraform Apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/
          auto_approve: true
          backend_config: >
            access_key=${{ secrets.AWS_ACCESS_KEY_ID }},
            secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }},
            bucket=${{ secrets.AWS_BUCKET }},
